### ISSUE TITLE
Sort the index consistently on both side

### ISSUE THREAD

**Issue by Tony-X** [Tony-X/search-benchmark-game#10]
This would enable generating controlled amount of deletions https://github.com/Tony-X/search-benchmark-game/issues/1

**Comment by Tony-X** [comment]
This [commit](https://github.com/Tony-X/search-benchmark-game/commit/8bf95a8203c780715b34dd77f8a972eb57837abc) introduced an `id` field on both side and sort the index by that.

**Comment by mikemccand** [comment]
Yay!  Thanks!
