### ISSUE TITLE
Too much variance in perf difference for the same class of queries

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#16]
Tantivy is substantially faster than Lucene, e.g. for `OrHighHigh` (disjunction of two high freq terms) queries.

But I'm baffled why the percent difference between the two engines is so wildly different even for queries matching 1M+ hits?

E.g.:

```
people nbsp | 4,004 μs1,167,748 docs | 8,867 μs +121.5 % 1,167,749 docs
```

and:

```
cite 2009 | 4,829 μs1,381,248 docs | 22,398 μs +363.8 % 1,381,266 docs
```

If Tantivy has a better postings decode (e.g. dedicated SIMD) it should be fairly uniformly faster for queries whose cost is dominated by postings decode.

**Comment by Tony-X** [comment]
Indeed! We should raise it to the tantivy community, too. 

To be honest, I don't believe the way the benchmark is setup would cause this.... but I could be wrong.

**Comment by Tony-X** [comment]
I think the current results are much better especially when we look at the `TOP_10_COUNT` case instead of `COUNT` , I'll resolve for now
