### ISSUE TITLE
Try benchmarking with SIMD disabled

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#18]
One possible approach to see how much of a gain Tantivy is seeing because it can specialize SIMD for postings lists decoding would be to run under a VM that blocks SIMD instructions.

**Comment by Tony-X** [comment]
I wonder what's the motivation of this? Is it to quantify the impact of SIMDs in isolation ?

**Comment by fulmicoton** [comment]
I'd love to see the result too. I suspect < 10% diff. 

Without SIMD, we fallback to a scalar implementation that is actually quite efficient too.

Some extra info on this:
The code that does this is in the bitpacking create.

It does not rely on compiler flags to decide whether to add in the SSE3 implem or not.
Instead it always adds it on x86 build and decide on which implementation to run at runtime.

sse3 is necessary for posting list
sse2 is sufficient for term frequencies.

If you want to add a feature flag to disable SIMD, I'm ok to merge that.

**Comment by mikemccand** [comment]
> I wonder what's the motivation of this? Is it to quantify the impact of SIMDs in isolation ?

Yeah that's exactly it.  Tantivy is clearly much faster than Lucene even on simple queries (as long as we resolve all the Benchmark Trust issues).  So let's try to isolate where the gains are coming from -- is it really that Rust execution is faster than JVM?  Or that Tantivy has better algorithms, e.g. the block encoding for postings, or its skip lists?  Is it from better access to SIMD instructions?  Something else?

Lucene also makes use of SIMD by "best effort" writing of the Java sources for postings decode so that the hotspot compiler will successfully auto-vectorize down to SIMD.  It's a fragile approach.

This issue was one simple way to take SIMD off the table, for both engines, to measure what it's contribution is to Tantivy's performance over Lucene.

**Comment by Tony-X** [comment]
> If you want to add a feature flag to disable SIMD, I'm ok to merge that.

I don't think we need to tinker this at tantivy level. I have a local run with RUSTC_FLAGS to disable sse2+ and avx2+, I can post the results later (it shows about ~10% difference). I tried but couldn't disable sse since LLVM somewhere uses it to pass return values.

**Comment by fulmicoton** [comment]
But that's disabling compiler vectorization too right? I think the JVM can use those, so it might not help @mikemccand to correctly assess the headroom associated with "handwritten" SIMD.

**Comment by Tony-X** [comment]
> But that's disabling compiler vectorization too right?

True. I think part of the goal here is to see the impact on tantivy itself by disabling the handwritten SIMD bitbacker as well as any vectorization that compiler can figure out. 

Even if it won't be fair to compare with Lucene, it can still shed some light to see for queries that tantivy has advantage, wether it can be solely explained by SIMD.

**Comment by Tony-X** [comment]
I don't know how to better share this....  Here is a screenshot. @fulmicoton you're right about the <10% diff. For some reasons I thought I saw a higher diff. 

<img width="1255" alt="image" src="https://github.com/Tony-X/search-benchmark-game/assets/7917591/450f8c7b-d0bd-4b08-a3d3-238aa8068025">

**Comment by Tony-X** [comment]
Here is the json result file.
[results.json.gz](https://github.com/Tony-X/search-benchmark-game/files/11671986/results.json.gz)


You can download and `make serve`

**Comment by fulmicoton** [comment]
The bitpacking stuff does not use avx. Sniping sse3 (and allowing avx) might be interesting.

**Comment by Tony-X** [comment]
For the record this is the flags used 
```
RUSTFLAGS="-C target-feature=-avx,-avx2,-ssse3
```

and this is my box's cpu flags
```
flags           : 
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush 
mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good
 nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3
 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c 
rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 
avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb 
avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
```

> The bitpacking stuff does not use avx

Maybe I missed something. As I was navigating myself in the code base I found that we check specifically for `avx2`
https://github.com/quickwit-oss/tantivy/blob/main/bitpacker/src/filter_vec/mod.rs#L21

**Comment by fulmicoton** [comment]
Yes :) It is a recent addition. We run range queries in Quickwit by building posting lists from a range and a column of values. We don't want to use trie-indexing to avoid doing too many GET requests.
The code is explained here:
https://quickwit.io/blog/filtering%20a%20vector%20with%20simd%20instructions%20avx-2%20and%20avx-512

This part of the cost is not used in your benchmark.

**Comment by Tony-X** [comment]
Aha, indeed! Upon further digging I realized that normal term queries (and the boolean combinations) do not excercise it. Thanks for confirming :)

BTW, that super interesting post along with the branchless binary search one are great reads. Please keep it up ❤️

**Comment by mikemccand** [comment]
Phew, lots of progress here!  Thanks @fulmicoton and @Tony-X!

> But that's disabling compiler vectorization too right? I think the JVM can use those, so it might not help @mikemccand to correctly assess the headroom associated with "handwritten" SIMD.

Right -- I'm not sure we can ask Hotspot not to autovectorize.  It's a good question.

**Comment by mikemccand** [comment]
> This part of the cost is not used in your benchmark.

Thanks -- that's a great point -- I opened a [spinoff to eventually benchmark doc values](https://github.com/Tony-X/search-benchmark-game/issues/34) as well.

**Comment by mikemccand** [comment]
> https://quickwit.io/blog/filtering%20a%20vector%20with%20simd%20instructions%20avx-2%20and%20avx-512

Thank you for writing and linking to this blog post -- it was fascinating!
