### ISSUE TITLE
Test on multi-segment indices?

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#20]
Tantivy may be using concurrency for a single query even on a single segment.

Maybe, to make the query latency comparisons more fair, we should create a multi-segment index, and use Lucene's concurrent (across segment) search?  This also better matches real-world usage for applications that need to continuously update their indices.

**Comment by Tony-X** [comment]
> Tantivy may be using concurrency for a single query even on a single segment.

Hmm, I don't think that is the case. I could double-check. In case Tantivy doesn't use more threads (or async IO within single thread) for a single segment, I believe the single-segment setup is a *fair* and simple in a good way (less variables) setup.

**Comment by mikemccand** [comment]
> > Tantivy may be using concurrency for a single query even on a single segment.
> 
> Hmm, I don't think that is the case. I could double-check. In case Tantivy doesn't use more threads (or async IO within single thread) for a single segment, I believe the single-segment setup is a _fair_ and simple in a good way (less variables) setup.

Yeah you are right -- when I watch CPU when `do_query` is running it is pegged at nearly 100%.

**Comment by mikemccand** [comment]
Also, this issue is a dup of #8.
