### ISSUE TITLE
`results.json` should include the category (`COUNT`, `TOP_10_COUNT`) in each query

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#25]
I pretty-printed the `results.json` from a full run.  It seems each task is executed twice (with N iterations each), yet the times vary quite a bit on each, for both Tantivy and Lucene:

```
beast3:search-benchmark-game[bind_all]$ grep -A 17 "\"+who +so\"" pretty1.txt
        "query": "+who +so",
        "tags": [
          "AndHighHigh"
        ],
        "count": 257789,
        "duration": [
          31627,
          31647,
          31655,
          31658,
          31661,
          31671,
          31675,
          31716,
          31720,
          31846
        ]
      },
--
        "query": "+who +so",
        "tags": [
          "AndHighHigh"
        ],
        "count": 257789,
        "duration": [
          37542,
          37566,
          37613,
          37614,
          37617,
          37634,
          37641,
          37648,
          37665,
          37708
        ]
      },
--
        "query": "+who +so",
        "tags": [
          "AndHighHigh"
        ],
        "count": 257789,
        "duration": [
          23350,
          23370,
          23399,
          23412,
          23413,
          23421,
          23438,
          23466,
          23511,
          23512
        ]
      },
--
        "query": "+who +so",
        "tags": [
          "AndHighHigh"
        ],
        "count": 257789,
        "duration": [
          25625,
          25647,
          25650,
          25665,
          25668,
          25682,
          25697,
          25709,
          25711,
          26451
        ]
      },
```

**Comment by mikemccand** [comment]
The first two results are two Tantivy runs for this query, and the latter two are Lucene.

**Comment by Tony-X** [comment]
Hey Mike, thanks for looking into this!

The query is executed twice that's because one for each mode. We current have "TOP_10_COUNT" as well as "COUNT" and COUNT will be faster. So we should look within the 10 iterations for checking the variance (and for this query it seems quite steady).

One idea here is that we can make the UI to output variance for latencies numbers

**Comment by mikemccand** [comment]
Oh!  Thank you for the clarification @Tony-X.  Hmm but the JSON output doesn't seem to indicate which is `COUNT` and which is `TOP_10_COUNT`?  Surely the faster one is `COUNT`.  I guess maybe the first one is always `COUNT` and the 2nd occurrence is always `TOP_10_COUNT`?

BTW, isn't it top 100 count now?  I thought we increase `topN` to 100 to match `luceneutil`?

**Comment by mikemccand** [comment]
> One idea here is that we can make the UI to output variance for latencies numbers

+1 -- `luceneutil` reports variance across its latencies (and across the 20 JVM runs).  I'll open a spinoff issue for this.  Though, the variances of the fastest 10 runs, for both Lucene and Tantivy, here, look quite tight.

**Comment by mikemccand** [comment]
Let's leave this issue open to maybe get the `results.json` to note which task type for each run?

**Comment by Tony-X** [comment]
Hmm, it is already organized in such way. It is certainly not quite readable for humans.

it is roughly as the following
```
{"Command": {"engine": [q1, q2, q3], "another_engine": [q1, q2, q3} ,
"Another_Command": {"engine": [q1, q2, q3], "another_engine": [q1, q2, q3} }
 
```

with large number of queries it is not obvious which command it is by looking at a specific query

**Comment by mikemccand** [comment]
OK I think the `results.json` form is fine -- it has all the information we need.  Thanks @Tony-X.
