### ISSUE TITLE
Can we disable BMW for both engines and test performance?

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#30]
This would let us separate out differences in how both engines use BMW for skipping.

**Comment by Tony-X** [comment]
Yes, this is already the case for both COUNT (there is no skipping involved to begin with) and TOP_10_COUNT (we made sure both engines do not skip)

Specifically for tantivy, we chain the count collector together with TopDocs  to achieve that.
```
            "TOP_10_COUNT" => {
                let (_top_k, count) = searcher.search(&query, &(TopDocs::with_limit(10), Count))?;
                println!("{}", count);
            }
```

For Lucene, we use `Integer.MAX_VALUE` for the `HitsThresholdChecker `
```
                        case "TOP_10_COUNT":
                        {
                            final TopScoreDocCollector topScoreDocCollector = TopScoreDocCollector.create(10, Integer.MAX_VALUE);
                            searcher.search(query, topScoreDocCollector);
                            int count = topScoreDocCollector.getTotalHits();
                            System.out.println(count);
                        }
```

**Comment by fulmicoton** [comment]
Tantivy has an interesting optimization for COUNT that could be used for Lucene.

I recommend using TopK + COUNT.

Otherwise you can write your own Collector, that does more or less nothing apart from scanning the docset. It is quite easy.


The optimisation Lucene could use: for disjunction we punch holes in a bitset of constant size (I think lucene does the same thing), and then iterate over the bitset using `msb`. For count, we pop count over this bitset, instead of iterating through it.

**Comment by Tony-X** [comment]
> I recommend using TopK + COUNT.

+1. At this point we probably should only focus the TopN + Count (no skipping) and TopN (with skipping)

> For count, we pop count over this bitset, instead of iterating through it.

For my curiosity, for it to work does it require the segment has no deletion?

**Comment by fulmicoton** [comment]
Tantivy deletion is not very optimized. We handle them as a post-process.
Oversimplified, collection looks like this:

```rust
for doc in docset {
   if alive_bitset.contains(&doc) {
      collector.collect(doc);
   }
}
```

(Note in that case, it could be done very efficiently by ANDing the bitsets.)

**Comment by mikemccand** [comment]
> I recommend using TopK + COUNT.
> 
> Otherwise you can write your own Collector, that does more or less nothing apart from scanning the docset. It is quite easy.

Maybe we should try both and pick the fastest?  I worry that the simple tuple of two collectors (`TopK` and `Count`) might be a bit slower than a custom Collector that just counts.

**Comment by mikemccand** [comment]
> The optimisation Lucene could use: for disjunction we punch holes in a bitset of constant size (I think lucene does the same thing), and then iterate over the bitset using `msb`. For count, we pop count over this bitset, instead of iterating through it.

This is a nice opto!  I opened https://github.com/apache/lucene/issues/12358 to explore porting it over to Lucene too.

**Comment by fulmicoton** [comment]
@mikemccand Awesome!

**Comment by Tony-X** [comment]
I'll close this one as we already disable BMW for the `TOP_10_COUNT` case.
