### ISSUE TITLE
Can we remove the `results.json` from git?

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#33]
I know it's nice to be able to checkout and immediately bring up the UI for browsing results...

But it's a bit misleading, since this did not run on your machine.

Also, `git diff` is massive if you've run benchmarks locally.

Finally, it is checked in in three different places (`results.json`, `web/public/results.json`, `web/build/results.json`), and it's confusing knowing which one "matters".

**Comment by Tony-X** [comment]
Indeed!

`web/public/results.json` is used a test data for developing the UI.
`web/build/results.json` is the one that is used to host from github pages.

arguably `results.json` could be removed since we expect successful runs will produce one. I guess we can add `results.json` to gitignore

**Comment by slow-J** [comment]
We removed the `results.json` from git in https://github.com/Tony-X/search-benchmark-game/commit/c6854ed3dbe77ab744f9ad652b232b3fa03b15b7.
This issue can be resolved.
