### ISSUE TITLE
Wrong Lucene version in build.gradle

### ISSUE THREAD

**Issue by uschindler** [Tony-X/search-benchmark-game#39]
This looks wrong, the version is outrdated. If the Lucene analyzers module is not used at all, we should remove it: https://github.com/Tony-X/search-benchmark-game/blob/4402d42c906830e85d8d79a30ae776f204ade770/engines/lucene-9.5.0/build.gradle#LL17C4-L17C4

**Comment by Tony-X** [comment]
Hi @uschindler, thanks for taking a look a this.

I used the [LengthFilter](https://github.com/Tony-X/search-benchmark-game/blob/4402d42c906830e85d8d79a30ae776f204ade770/engines/lucene-9.5.0/src/main/java/BuildIndex.java#L90) to remove excessively long tokens. So the analyzer module is needed.

> This looks wrong, the version is outrdated. 

Indeed the version is one minor release behind, now we have 9.6.0. We should upgrade. Do you believe this will lead to wrong performance conclusions? I did not spot major query performance changes by a quick glance of the [changelog](https://lucene.apache.org/core/9_6_0/changes/Changes.html#v9.6.0.optimizations)

**Comment by mikemccand** [comment]
Lucene is now up to 9.7.0, and Tantivy is 0.20.1 -- let's upgrade both?
