### ISSUE TITLE
Confirm that TOP_N hits returned match in both engines

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#4]
Let's confirm the two engines are returning the same/correct hits before concluding anything about performance?

**Comment by mikemccand** [comment]
We could do this as a weighted overlap measure too (e.g. NDCG).

**Comment by Tony-X** [comment]
I made a change to enable comparing results by pure set overlap. Later we can add different / more metrics.

Both sides are allowed to skip with BMW. This query set excluded sloppy phrase query since there is a known difference.

```
➜  search-benchmark-game git:(luceneutil) ✗ make overlap_100
--- Running Overalp Test (compare top 100) ---
engines: left: `tantivy-0.19`, right: `lucene-9.5.0`
/local/home/tonyx/wss/search-benchmark-game/engines/tantivy-0.19
/local/home/tonyx/wss/search-benchmark-game/engines/lucene-9.5.0
p000:   0.15
p005:   0.99
p010:   0.99
p015:   1.00
p020:   1.00
p025:   1.00
p030:   1.00
p035:   1.00
p040:   1.00
p045:   1.00
p050:   1.00
p055:   1.00
p060:   1.00
p065:   1.00
p070:   1.00
p075:   1.00
p080:   1.00
p085:   1.00
p090:   1.00
p095:   1.00
p100:   1.00
mean:   1.00
Low overlap queries:
0.15
some
['HighTerm']
0.57
group
['MedTerm']
0.9
pdf
['MedTerm']
0.95
w
['MedTerm']
0.79
t
['MedTerm']
0.95
source
['MedTerm']
0.94
co
['MedTerm']
0.5268817204301075
htm
['MedTerm']
0.87
groups
['MedTerm']
0.8
lpg
['LowTerm']
0.9
comparison
['LowTerm']
0.95
express
['LowTerm']
0.4
d.c
['LowTerm']
0.95
150px
['LowTerm']
0.95
124
['LowTerm']
0.95
lt
['LowTerm']
0.9
vision
['LowTerm']
0.92
modified
['LowTerm']
0.94
+more +7
['AndHighHigh']
0.6666666666666666
+than +か
['AndHighLow']
0.95
all during
['OrHighHigh']
0.95
see 10
['OrHighHigh']
0.92
10 out
['OrHighHigh']
0.92
one ian
['OrHighMed']
0.93
name w.p
['OrHighLow']
0.32
some adf
['OrHighLow']
0.34
some aston
['OrHighLow']
0.47
some fermi
['OrHighLow']
0.95
"bot generated"
['MedPhrase']
0.94
"any race"
['MedPhrase']
0.92
"every 100"
['LowPhrase']
0.93
"100 females"
['LowPhrase']
0.62
"computer science"
['LowPhrase']
0.91
"racial makeup"
['LowPhrase']
0.9
"average household"
['LowPhrase']
0.92
"had children"
['LowPhrase']
0.95
"square mile"
['LowPhrase']
0.93
"females age"
['LowPhrase']
0.93
"18 living"
['LowPhrase']
0.89
"households were"
['LowPhrase']
0.94
"families residing"
['LowPhrase']
0.91
"households out"
['LowPhrase']
```


most of queries return same results (5144 queries), there are some "noise" terms like `some`,  `htm` I guess due to tokenization issue they end up with quite different results

**Comment by Tony-X** [comment]
https://github.com/Tony-X/search-benchmark-game/commit/aaa66f288933183dd8415ce2bc9c24a82ea7c110

**Comment by Tony-X** [comment]
It'd be nice if we can present this in the UI, too.

**Comment by Tony-X** [comment]
I introduced this commit to make the tokenization on the both side more similar to each other. The results is much better now, but still not perfect. I looked closer at this query  `+than +か` and realized that Lucene also handles the unicode whitespaces while current Tantivy's WhiteSpaceTokenizer handles just ASCII spaces. See here https://github.com/quickwit-oss/tantivy/blob/main/src/tokenizer/whitespace_tokenizer.rs#L33

```
➜  search-benchmark-game git:(luceneutil) ✗ make overlap_100 
--- Running Overalp Test (compare top 100) ---
engines: left: `tantivy-0.19`, right: `lucene-9.5.0`
/local/home/tonyx/wss/search-benchmark-game/engines/tantivy-0.19
/local/home/tonyx/wss/search-benchmark-game/engines/lucene-9.5.0
p000:   0.67
p005:   1.00
p010:   1.00
p015:   1.00
p020:   1.00
p025:   1.00
p030:   1.00
p035:   1.00
p040:   1.00
p045:   1.00
p050:   1.00
p055:   1.00
p060:   1.00
p065:   1.00
p070:   1.00
p075:   1.00
p080:   1.00
p085:   1.00
p090:   1.00
p095:   1.00
p100:   1.00
mean:   1.00
Low overlap queries:
0.95
+author +however
['AndHighHigh']
0.6666666666666666
+than +か
['AndHighLow']
0.94
date thumb
['OrHighHigh']
```

**Comment by Tony-X** [comment]
I think the results are close enough -- we can fix the unicode whitespace problem for tantivy later

**Comment by fulmicoton** [comment]
The score are supposed to be the same if you search in one field only.

Preprocessing the text to make sure tokenization is not a problem (removing punctations and putting whitespace between tokens for instance) might be a good idea.

**Comment by Tony-X** [comment]
Pre-processing is one way to go. Here I try to reuse the corpus used by lucenutil as much as we can. 

I forked the `WhitespaceTokenizer` to split at unicode spaces, too. With that [change](https://github.com/Tony-X/search-benchmark-game/commit/a6f71237e84aeb47ee8f5b923f16b760b032e1fc) the results are almost perefct.

> The score are supposed to be the same if you search in one field only.

I did separately check for a bunch of queries and indeed the score are the "same" -- Lucene and Tantivy use same k1 and b for BM25. Tantivy does not multiply the constant `k1 + 1` so the scores differ by that factor.

However, here we are simply doing set intersection for now. We could use position-weighted measure such as NDCG

```
➜  search-benchmark-game git:(luceneutil) ✗ make overlap_100 
--- Running Overalp Test (compare top 100) ---
engines: left: `tantivy-0.19`, right: `lucene-9.5.0`
/local/home/tonyx/wss/search-benchmark-game/engines/tantivy-0.19
/local/home/tonyx/wss/search-benchmark-game/engines/lucene-9.5.0
p000:   0.94
p005:   1.00
p010:   1.00
p015:   1.00
p020:   1.00
p025:   1.00
p030:   1.00
p035:   1.00
p040:   1.00
p045:   1.00
p050:   1.00
p055:   1.00
p060:   1.00
p065:   1.00
p070:   1.00
p075:   1.00
p080:   1.00
p085:   1.00
p090:   1.00
p095:   1.00
p100:   1.00
mean:   1.00
Low overlap queries:
0.95
+author +however
['AndHighHigh']
0.94
date thumb
['OrHighHigh']
```

**Comment by Tony-X** [comment]
I raise a PR to add this improvement to tantivy's WhitespaceTokenizer

https://github.com/quickwit-oss/tantivy/pull/2082

**Comment by mikemccand** [comment]
This is great @Tony-X!  So close to perfect overlap.

```
Low overlap queries:
0.95
+author +however
['AndHighHigh']
0.94
date thumb
['OrHighHigh']
```

So now I'm curious what's causing this tiny difference...

**Comment by Tony-X** [comment]
> So now I'm curious what's causing this tiny difference...

@mikemccand  I think there are still some tiny tiny differences in tokenization...
