### ISSUE TITLE
Test with the throughput GC, not G1GC (the default)

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#45]
@uschindler pointed out on an [upstream Lucene issue](https://github.com/apache/lucene/issues/12358#issuecomment-1585595163) that G1GC may not be "best" for measuring Lucene's single-threaded performance, and we should use the throughput collector instead.  This collector will stop-the-world (causing any running queries to take crazy long, but they would be discarded as outliers by the benchy) in exchange for minimal net CPU cost spent on GC.

It's simple to enable the throughput collector (`-XX:+UseParallelGC` I think).  We should test if this makes any difference in the benchmark.

HOWEVER, it's hard to know if this is the "right thing to do".  Yes, on the one hand, if we are trying to purely measure CPU cost of Lucene's querying, G1GC is a bit unfair since it adds some continuous cost due to memory guards on reads, though it seems likely most of those reads won't be blocked on G1GC having to suddenly move an object.  But on the other hand, in a production context for searching, most applications will not use the throughput collector but rather G1GC or maybe CMS, and so G1GC would reflect the "real world" cost of doing business in javaland.

Still we should run this test to at least see the impact.

**Comment by slow-J** [comment]
We enabled the throughput GC with https://github.com/Tony-X/search-benchmark-game/commit/4402d42c906830e85d8d79a30ae776f204ade770 .
The final step is to run a comparison benchmark.

**Comment by slow-J** [comment]
Tested Lucene 9.7 with g1gc (by removing the `UseParallelGC` flag) vs with throughput GC (mainline). Attaching the json. [results_m5.12xlarge_lucene_9_7_g1gcvsthroughputgc.json.zip](https://github.com/Tony-X/search-benchmark-game/files/12368637/results_m5.12xlarge_lucene_9_7_g1gcvsthroughputgc.json.zip)

Hardware used: m5.12xlarge EC2 instance with `x86_64` architecture.


The difference in COUNT is minuscule, a 0.72% average improvement by using the throughput GC.

![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/22505b11-9ea0-4853-98bd-865269add913)

Performance of TOP_10_COUNT is more affected with a 3.12% improvement by using the throughput GC.
![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/dde26d03-8348-4af7-90de-552deb302a8e)

**Comment by mikemccand** [comment]
Ooh -- we had already switched to the throughput collector, OK.

Thanks for testing @slow-J -- interesting how much it helps for top hits collection.

I think this falls into the "so this contributes to the performance difference between Rust/Java Tantivy/Lucene, but, this is really the 'cost of doing business' in Java".  I.e. in production most search engines would likely choose G1GC for the minimal-ish impact on long-pole latencies, even if it increases the average latencies.

I'll download the JSON and poke around.  Thanks for uploading!  I wish we (anyone) could interact with the UI here after uploading the `results.json` ...

**Comment by mikemccand** [comment]
Wow, for `AndHighHigh` (conjunction of two high frequency terms) the gains are even more, ~4.8% for average query latency:

![Screenshot 2023-08-17 at 8 02 59 AM](https://github.com/Tony-X/search-benchmark-game/assets/796508/db44ede5-d45a-4a7e-95fc-29b717fadca7)

**Comment by slow-J** [comment]
Closing this issue since I cannot see any items to follow up on.
