### ISSUE TITLE
Bug: if you run a single COMMAND that is not COUNT, you cannot view the results.

### ISSUE THREAD

**Issue by slow-J** [Tony-X/search-benchmark-game#53]
Repro: set `COMMANDS ?= TOP_10`

Result:
![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/101fc7f3-da30-4489-bec6-fb4289411dfa)

If you duplicate and rename `TOP_10` in the result.json, you can view a report by changing selection.

Therefore I am guessing that since `state.mode` of `Benchmark` defaults to `COUNT` and we only have 1 key (which is not `COUNT`) therefore we cannot change the mode `onChange`?

I can't confirm this since I am unable to rebuild the web UI.
As part of this, we should update the development guide with instructions on how to do so.

**Comment by mikemccand** [comment]
`+1` for instructions on how to rebuild the UI!  Does anyone know how?

**Comment by slow-J** [comment]
I think `yarn build` is enough to rebuild the UI. We specifically need Node 18/19 or there are dependency issues with node-sass.
Although the website that yarn/npm loads, is from some out of date json. You still have to `make serve_local` to see your `results.json` and the UI changes.
