### ISSUE TITLE
Upgrade & re-test latest Tantivy and Lucene

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#57]
There have been a number of search-time optimizations inspired by Tantivy folded into Lucene lately.  And I'm sure Tantivy is making improvements too!  Let's re-upgrade to the latest & greatest and re-test?

**Comment by slow-J** [comment]
Will try to get this upgraded today, currently running the benchmark.

**Comment by slow-J** [comment]
Comparing the new change (left) to the [prod website](https://tony-x.github.io/search-benchmark-game/) (right).

Same setup used in test as in the prod website:
* Ran on m5.12xlarge machine
* JDK 20
* Rust 1.71.1

![Screenshot 2023-11-06 at 16 36 34](https://github.com/Tony-X/search-benchmark-game/assets/32519034/1a1d9a0d-74a2-4bf4-b02f-6ce34bc61ab6)
![Screenshot 2023-11-06 at 16 36 23](https://github.com/Tony-X/search-benchmark-game/assets/32519034/1b8501dd-6648-4f76-84b5-4327a2c20917)
![Screenshot 2023-11-06 at 16 36 11](https://github.com/Tony-X/search-benchmark-game/assets/32519034/ce5fdca0-4919-4997-9e66-66079d3b73d9)


Lucene has improved in the benchmark between 9.7->9.8 with COUNT (-16%) and TOP_100 (-14%)

**Comment by slow-J** [comment]
Results.json from results above.

[results.json](https://github.com/Tony-X/search-benchmark-game/files/13270059/results.json)
