### ISSUE TITLE
Run more iterations per task

### ISSUE THREAD

**Issue by mikemccand** [Tony-X/search-benchmark-game#6]
Three iterations only leaves room for substantial noise (GC, hotspot, etc.).

Can we increase to 50 iterations, discard first N (10?) as warmup, and then take fastest time of the remaining 40 tasks.

Let's see if that makes the %tg difference b/w the two engines more consistent, especially for the high hit count cases.

**Comment by Tony-X** [comment]
Currently we run 10 iterations and I made it configurable, too. I think the results didn't change much as compared to running 3 iterations.
