### ISSUE TITLE
Use min latency for both engines to eliminate noise

### ISSUE THREAD

**Issue by Tony-X** [Tony-X/search-benchmark-game#9]
This is especially important for Lucene, since there could be GC

**Comment by Tony-X** [comment]
I double checked the code and verified that it is already taking the min across iterations.

**Comment by zhaih** [comment]
> since there could be GC

I actually was thinking about the opposite: shouldn't GC be part of Lucene/java as we always have GC in production, so isn't choosing average (which contains some light GC runs as well as some heavy GC runs) the better way to compare the performance?

**Comment by Tony-X** [comment]
I would agree with you if we lift this benchmark to test peak load performance. in that case the percentile latency would be helpful, too.

Currently, the benchmark is geared towards measure the best case scenario to get the same task done as a proxy to probe the underlying efficiency difference while trying to eliminate outliers (those impacted by GC, cold start, etc)
